#!/bin/bash

apt-get install -y autogen
mkdir -p /tmp
cd /tmp
git clone https://github.com/facebook/watchman.git
cd watchman
git checkout v4.7.0  # the latest stable release
./autogen.sh
./configure
make
make install
